### ISSUE TITLE
ASDF does not always properly resolve tag references in schema files

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/asdf#367]
Consider the following example schema:
```yaml
%YAML 1.1
---
$schema: "http://stsci.edu/schemas/asdf/asdf-schema-1.0.0"
id: "http://stsci.edu/schemas/asdf/nugatory/nugatory-1.0.0"
tag: "tag:stsci.edu:asdf/nugatory/nugatory-1.0.0"

type: object
properties:
  foobar:
      $ref: "../core/ndarray-1.0.0"

required: [foobar]
...
```

In this case, the tag reference is expressed as a URI relative this schema's full URI. It is properly resolved by ASDF.

However, JSON schema allows references to be expressed as [tag URIs](https://en.wikipedia.org/wiki/Tag_URI_scheme) as well:
```yaml
%YAML 1.1
---
$schema: "http://stsci.edu/schemas/asdf/asdf-schema-1.0.0"
id: "http://stsci.edu/schemas/asdf/nugatory/nugatory-1.0.0"
tag: "tag:stsci.edu:asdf/nugatory/nugatory-1.0.0"

type: object
properties:
  foobar:
      $ref: "tag:stsci.edu:asdf/core/ndarray-1.0.0"

required: [foobar]
...
```

This does not currently work in ASDF.

It is also possible express references as full URIs (i.e. not necessarily relative to the schema's own URI):
```yaml
%YAML 1.1
---
$schema: "http://stsci.edu/schemas/asdf/asdf-schema-1.0.0"
id: "http://stsci.edu/schemas/asdf/nugatory/nugatory-1.0.0"
tag: "tag:stsci.edu:asdf/nugatory/nugatory-1.0.0"

type: object
properties:
  foobar:
      $ref: "http://example.org/schemas/example/foo/foo-1.0.0"

required: [foobar]
...
```

I believe that this does not work when the URI in the reference does not belong to the same organization and standard as the schema's own URI. More investigation is required.
