### ISSUE TITLE
Recursive references serialize and deserialize incorrectly

### ISSUE THREAD

**Issue by eslavich** [spacetelescope/asdf#745]
A simple example from a discussion with @jdavies-st:

```python
In [16]: target = {"foo": "bar"}
    ...: target["nested"] = target
    ...: af = asdf.AsdfFile(tree)
    ...: af.info()
root.tree (AsdfObject)
└─target (dict)
  ├─foo (str): bar
  └─nested (dict)
    ├─foo (str): bar
    └─nested (dict) (recursive reference)
```
Surprise!  Somehow we ended up with more distinct objects than we started with.  The display from info() is correctly depicting the situation:
```python
In [17]: af["target"] is af["target"]["nested"]
Out[17]: False

In [18]: af["target"]["nested"] is af["target"]["nested"]["nested"]
Out[18]: True
```
That's fine, we can create the recursive tree another way:
```python
In [20]: target = {"foo": "bar"}
    ...: target["nested"] = target
    ...: af = asdf.AsdfFile()
    ...: af.tree["target"] = target
    ...: af.info()
root.tree (AsdfObject)
└─target (dict)
  ├─foo (str): bar
  └─nested (dict) (recursive reference)
```
That's more like it.  Now serialize:
```python
In [21]: af.write_to("test.asdf")
    ...: print(open("test.asdf").read())
```
```
#ASDF 1.0.0
#ASDF_STANDARD 1.4.0
%YAML 1.1
%TAG ! tag:stsci.edu:asdf/
--- !core/asdf-1.1.0
asdf_library: !core/software-1.0.0 {author: Space Telescope Science Institute, homepage: 'http://github.com/spacetelescope/asdf',
  name: asdf, version: 2.5.2a1.dev15+g90e5a4e.d20200130}
history:
  extensions:
  - !core/extension_metadata-1.0.0
    extension_class: asdf.extension.BuiltinExtension
    package: !core/software-1.0.0 {name: asdf, version: 2.5.2a1.dev15+g90e5a4e.d20200130}
target:
  foo: bar
  nested: &id001
    foo: bar
    nested: *id001
...
```
The object was serialized with YAML anchors and aliases, which is legal but unexpected, since the asdf standard recommends using `$ref` instead.  When we ask asdf to read the file again:
```python
asdf.open("test.asdf").info()
```
```
root.tree (AsdfObject)
├─asdf_library (Software)
│ ├─author (str): Space Telescope Science Institute
│ ├─homepage (str): http://github.com/spacetelescope/asdf
│ ├─name (str): asdf
│ └─version (str): 2.5.2a1.dev15+g90e5a4e.d20200130
├─history (dict)
│ └─extensions (list)
│   └─[0] (ExtensionMetadata)
└─target (dict)
  ├─foo (str): bar
  └─nested (dict)
    ├─foo (str): bar
    └─nested (dict)
      ├─foo (str): bar
      └─nested (dict)
        ├─foo (str): bar
        └─nested (dict) (recursive reference)
```

It did eventually figure out the recursive link, but only after running in circles an extra 3 times.

So a few things to fix/resolve here:
- Building a file from a tree with recursive references shouldn't add an extra layer of unique objects
- Should trees be serialized with `$ref` instead of anchors/aliases?  What happens when you deserialize a tree with a `$ref`?
- Trees with anchors/aliases should deserialize correctly

This is related to #744 but is a distinct issue.
