### ISSUE TITLE
usage of oneOf for schema validation

### ISSUE THREAD

**Issue by CagtayFabry** [spacetelescope/asdf#809]
I am having trouble getting my schemas to validate when using `oneOf` structures. (running asdf=2.6.0, python=3.7)

Consider the following python/asdf example that I expected to work but somehow cannot implement.
```python
#python class for debugging
@dataclass
class OneOfClass:
    data: dict


class OneOfClassType(CustomType):
    name = "debug/oneOf_class"
    version = "1.0.0"
    types = [OneOfClass]

    @classmethod
    def to_tree(cls, node: OneOfClass, ctx):
        return node.data

    @classmethod
    def from_tree(cls, tree, ctx):
        obj = OneOfClass(tree)
        return obj
```
The schema I wanted to implement:
```yaml
%YAML 1.1
---
$schema: "http://stsci.edu/schemas/yaml-schema/draft-01"
id: "http://somewhere.com/schemas/debug/oneOf_class-1.0.0"
tag: "tag:somewhere.com:debug/oneOf_class-1.0.0"

title: |
  oneOf test schema
oneOf:
  - type: object
    properties:
      value:
        type: number
    required: [value]
    additionalProperties: false

  - type: object
    properties:
      value:
        type: string
    required: [value]
    additionalProperties: false
...
```

Now the following will fail:
```python
with asdf.AsdfFile(
    tree={"obj_a": OneOfClass({"value": "a string"})},
    extensions=[CustomExtension()],
) as ff:
    ff.write_to("oneOf.asdf")
```

```python
jsonschema.exceptions.ValidationError: {'value': 'a string'} is valid under each of OrderedDict([('type', 'object'), ('properties', OrderedDict([('value', OrderedDict([('type', 'string')]))])), ('required', ['value']), ('additionalProperties', False)]), OrderedDict([('type', 'object'), ('properties', OrderedDict([('value', OrderedDict([('type', 'number')]))])), ('required', ['value']), ('additionalProperties', False)])
```

If I only keep the string part of the schema as the single `oneOf` entry, it works. (same when trying to store a number, only works when the number part is the only `oneOf` list entry)
```yaml
oneOf:
#  - type: object
#    properties:
#      value:
#        type: number
#    required: [value]
#    additionalProperties: false

  - type: object
    properties:
      value:
        type: string
    required: [value]
    additionalProperties: false
...
```

When changing `oneOf` to `allOf` I get `jsonschema.exceptions.ValidationError: 'a string' is not of type 'number'`
Using `anyOf` in the original example works.

While I can get by using `anyOf` I would prefer `oneOf` for clarity and peace of mind. Any hints are appreciated.

**Comment by eslavich** [comment]
Thanks for the report!  This looks like an asdf bug.  I was able to successfully validate your example instance and schema using the jsonschema library directly, so asdf must be muddying the issue somehow.  I should be able to look into this later today.

**Comment by eslavich** [comment]
The validation failure is raised by the asdf code for removing default values, and not the actual validation pass.  That code uses the oneOf combiner to traverse the schema, but disables all actual validation, so oneOf ends up failing because all subschemas report zero errors.

Unfortunately while we have a flag to disable filling defaults on read, we have no such flag to disable removing defaults on write.  I think until we get this fixed your best option is to get by with `anyOf`.

Incidentally, we're planning to deprecate the feature that fills/removes default values from schemas.  If a real fix turns out to be high effort, we may want to just add the missing flag instead.  Would that work for you?

**Comment by CagtayFabry** [comment]
Thank you for looking into this @eslavich 
I almost suspected some interference with default values after looking through other issues but my understanding is too limited to dig into it myself.

I will stick with `anyOf` for now and try to keep each case as tight as possible in cases where I would otherwise put `oneOf`.

I have not really used or relied on default values so far but putting a flag should not be a problem.

**Comment by eslavich** [comment]
@CagtayFabry the fix for this turned out to be straightforward.  It's in master if you'd like to give it a try.

**Comment by Jerry-Ma** [comment]
I just found that PR 811 have made the following schema invalid:

```
%YAML 1.1
---
$schema: "http://stsci.edu/schemas/yaml-schema/draft-01"
id: "example.com/schemas/example/nddataframe-1.0.0"
title: |
  An n-dimensional index frame.
description: |
  This frame is an abstraction of the indices of an n-dimensional array.

type: object
properties:
  name:
    description: |
      A user-friendly name for the frame.
    type: string

  anyOf:
    - naxes:
      description: |
        The number of axes.
      type: integer

    - axes_order:
        description: |
          The order of the axes.
        type: array
        items:
          type: integer

anyOf:
  - required: [name, naxes]
  - required: [name, axes_order]
additionalProperties: true
...
```

The error happens when parsing the `anyOf` in properties. The subschema is found to be the list of that anyOf around asdf/schema.py, line 191, function validate_remove_default.

**Comment by eslavich** [comment]
Hi @Jerry-Ma this is not a valid schema.  `anyOf` is not permitted in a list of properties.  I think this may be equivalent:
```yaml
type: object
properties:
  name:
    description: |
        A user-friendly name for the frame.
    type: string

  naxes:
    description: |
      The number of axes.
    type: integer

  axes_order:
    description: |
        The order of the axes.
    type: array
    items:
        type: integer

anyOf:
  - required: [name, naxes]
  - required: [name, axes_order]
additionalProperties: true
```
This schema will validate any of the following:
```yaml
name: some name
naxes: 4
```
```yaml
name: some name
axes_order: [1, 2, 3, 4]
```
```yaml
name: some name
naxes: 4
axes_order: [1, 2, 3, 4]
```
but will fail this:
```yaml
name: some name
```
